---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=Etc/UTC
    # volumes:
    #   - ./config:/config
    ports:
      - 3002:3000
      - 3003:3001
    # devices:
    #   - /dev/dri:/dev/dri #optional
    # shm_size: "1gb"
    restart: unless-stopped
